name: sentiment_analyzer_agent
description: Analyzes sentiment of the transcript
entry_point: sentiment_analyzer.py
requirements:
  - openai
triggers:
  - type: manual
    input: transcript
output:
  type: json
  fields:
    - sentiment  # e.g., positive, negative, neutral
