name: youtube_transcriber
description: Transcribes YouTube video audio to text
entry_point: transcriber.py
requirements:
  - yt-dlp
  - openai
  - whisper
triggers:
  - type: manual
    input: youtube_url
output:
  type: json
  fields:
    - transcript
